services:
  qdb:
    image: postgres:15.3-alpine
    container_name: qdb
    restart: unless-stopped
    env_file:
      - dbp.env
    ports:
      - "5439:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - qbpgdata:/var/lib/postgresql/data
      - qbpgconf:/etc/postgresql
      - qbpglog:/var/log/postgresql
  qbittal:
    depends_on: [qdb]
    container_name: qbittal
    image: kalairen/qbittal:latest
    restart: unless-stoppeds
    environment:
      - QBITTORRENT_API=https://qbittorrent.example.com
      - QBITTORRENT_USER=admin
      - QBITTORRENT_PASSWORD=admin
    ports:
      - 8061:8061

volumes:
  qbpgdata:
    driver: local
  qbpgconf:
    driver: local
  qbpglog:
    driver: local
